/**
 * 多语言词条。
 * 只改这里就能改全站文案（HTML 里用 data-i18n / data-i18n-placeholder 引用 key）。
 * scripts/check.mjs 会校验：页面里出现的每个 key 在 zh / en 中都必须存在。
 */
window.OING_I18N = {
  zh: {
    'meta.title': 'Oing — 让智能更近一步',
    'meta.description': 'Oing 是一个专注于理解与创造的通用智能助手。提问、写作、编程、分析，从一句话开始。',

    'a11y.skip': '跳到主要内容',

    'nav.capability': '能力',
    'nav.news': '动态',
    'nav.legal': '法务',
    'header.cta': 'GitHub',

    'announce.text': '官网已上线，产品仍在开发中。',
    'announce.more': '查看详情',

    'hero.slogan': '让智能更近一步',
    'composer.label': '输入你的问题',
    'composer.placeholder': '有什么想知道的？',
    'composer.attach': '添加附件',
    'composer.reason': '深度思考',
    'composer.search': '联网搜索',
    'ask.note': '这里只回答关于本站、已经确认过的问题。答案是手写的，答不上来会直说。',
    'ask.noteRemote': '常见问题是手写答案，没写在里面的会交给语言模型 —— 它被限制为只能依据站内已确认的事实回答。',
    'ask.thinking': '正在查，可能要几秒…',
    'ask.remoteSrc': '这条由语言模型依据站内已确认事实生成。',
    'ask.you': '你问',
    'ask.foot': '答案都是手写的。如有出入，欢迎邮件指出：',
    'ask.chipsLabel': '常见问题',
    'ask.chip1': '这到底是什么？',
    'ask.chip2': '什么时候能用？',
    'ask.chip3': '怎么联系你们？',
    'ask.chip4': '和 DeepSeek 什么关系？',
    'ask.chip5': '会不会收费？',
    'hero.action.github': '在 GitHub 上关注',
    'hero.action.news': '了解进展',

    'cap.eyebrow': 'Capabilities',
    'cap.title': '能力',
    'cap.note': '以下为正在开发中的能力，目前均未开放使用。',
    'cap.1.t': '深度推理',
    'cap.1.d': '面对多步难题先想清楚再回答，推理路径可追溯。',
    'cap.2.t': '联网搜索',
    'cap.2.d': '需要最新信息时自动检索，并给出可核对的来源。',
    'cap.3.t': '超长上下文',
    'cap.3.d': '整本手册、整份财报一次读进来，不丢细节。',
    'cap.4.t': '代码与工具',
    'cap.4.d': '读懂整个仓库，调用函数与外部工具完成任务。',
    'cap.5.t': '多模态理解',
    'cap.5.d': '图片、表格、扫描件，看懂之后再动笔。',
    'cap.6.t': '可控与安全',
    'cap.6.d': '数据用途透明，权限边界清晰，随时可以撤回。',

    'news.eyebrow': 'Updates',
    'news.title': '动态',
    'news.1.t': '官网已上线',
    'news.1.d': '首页、能力说明与法务页面已就绪。',
    'news.2.t': '产品开发中',
    'news.2.d': '对话与开放平台尚未开放，进展会更新在这里。',

    'footer.slogan': '让智能更近一步。',
    'footer.col2': '法务',
    'footer.terms': '服务条款',
    'footer.privacy': '隐私政策',
    'footer.disclaimer': '免责声明',
    'footer.col3': '关于',
    'footer.contact': '联系我们',
    'footer.github': 'GitHub',
    'footer.rights': '保留所有权利',

    'msg.notConfigured': '这个入口还没有配置，暂时用不了。',
    'msg.sent': '对话功能还在开发中，目前还不能用。',
    'msg.attached': '附件功能还在开发中，目前还不能用。',
    'msg.emailCopied': '邮箱已复制，粘贴到你的邮件里即可。',
    'msg.theme.light': '已切换为浅色',
    'msg.theme.dark': '已切换为深色',

    'legal.title': '法务信息',
    'legal.updated': '最近更新：2026-10-02',
    'legal.terms.t': '服务条款',
    'legal.terms.p1': '本站是 Oing 的官方展示页面，为纯静态站点：不提供任何在线服务，没有账号系统，也没有付费功能。',
    'legal.terms.p2': '站内文字、图形与代码的知识产权归本站所有或已获授权。你可以自由浏览和分享链接；如需整页转载，请先与我们联系。',
    'legal.terms.p3': '本站可能随时变更内容、暂停或关闭，恕不另行通知。继续浏览即表示你接受本条款。',
    'legal.privacy.t': '隐私政策',
    'legal.privacy.p1': '本站不收集任何个人数据：没有账号、没有表单提交、没有埋点，也不接入任何第三方统计或广告脚本。',
    'legal.privacy.p2': '本站会在你的浏览器里本地存储两项偏好 —— 明暗主题与界面语言。它们只保存在你自己的设备上，不会发送到任何服务器；清除浏览器数据即可删除。',
    'legal.privacy.p3': '本站托管在 GitHub Pages，域名解析由 Cloudflare 提供。这两家服务商可能按其各自的隐私政策记录访问日志（例如 IP 地址、User-Agent）。本站不主动收集、也不分析这些数据，对它们的记录行为既无法访问也无法控制。',
    'legal.privacy.p4': '如果你在首页的问答框里提问：常见问题由站内事先写好的答案直接回答，问题内容不会离开你的浏览器。只有当问题不在这些答案里时，它才会被发送到本站的服务端接口，并转发给模型服务聚合平台 OpenRouter 用于生成回答。本站不保存提问内容；OpenRouter 及其上游模型提供方可能按其各自的政策记录请求。如果你不希望这样，请不要使用那个输入框 —— 站内所有其它内容都不需要联网。',
    'legal.privacy.p5': '如果你通过邮件联系我们，我们只会用你的邮箱地址回复该问题，不会用于其它用途，也不会提供给第三方。',
    'legal.disclaimer.t': '免责声明',
    'legal.disclaimer.p1': '站内介绍的产品与功能处于开发中状态，描述可能随时调整，不构成任何承诺或要约。',
    'legal.disclaimer.p2': '站内的 Oing 名称与图形为本站所有。本站与任何第三方公司、产品或商标均无关联，也未获其授权或认可。',
    'legal.disclaimer.p3': '本站对外部链接指向的内容不承担责任。',
    'legal.contact.t': '联系我们',
    'legal.contact.p': '如有任何疑问，欢迎邮件联系。',
    'legal.back': '返回首页',

    'nf.title': '页面走丢了',
    'nf.sub': '你访问的地址不存在，或者已经被移动到别处。',
    'nf.home': '回到首页',
  },

  en: {
    'meta.title': 'Oing — Closer to intelligence',
    'meta.description': 'Oing is a general-purpose assistant built for understanding and creating. Ask, write, code, analyse — starting from one sentence.',

    'a11y.skip': 'Skip to main content',

    'nav.capability': 'Capabilities',
    'nav.news': 'Updates',
    'nav.legal': 'Legal',
    'header.cta': 'GitHub',

    'announce.text': 'The site is live. The product is still in development.',
    'announce.more': 'Read more',

    'hero.slogan': 'Closer to intelligence',
    'composer.label': 'Type your question',
    'composer.placeholder': "What's on your mind?",
    'composer.attach': 'Attach a file',
    'composer.reason': 'Deep think',
    'composer.search': 'Web search',
    'ask.note': 'This only answers confirmed questions about this site. Answers are hand-written; if it does not know, it says so.',
    'ask.noteRemote': 'Common questions use hand-written answers. Anything else goes to a language model limited to the confirmed facts on this site.',
    'ask.thinking': 'Looking that up — this can take a few seconds…',
    'ask.remoteSrc': 'This one was generated by a language model from the confirmed facts on this site.',
    'ask.you': 'You asked',
    'ask.foot': 'Answers are hand-written. If something looks wrong, email us:',
    'ask.chipsLabel': 'Common questions',
    'ask.chip1': 'What is this?',
    'ask.chip2': 'When can I use it?',
    'ask.chip3': 'How do I contact you?',
    'ask.chip4': 'Are you related to DeepSeek?',
    'ask.chip5': 'Will it cost money?',
    'hero.action.github': 'Follow on GitHub',
    'hero.action.news': 'See progress',

    'cap.eyebrow': 'Capabilities',
    'cap.title': 'Capabilities',
    'cap.note': 'These capabilities are in development and none of them are available yet.',
    'cap.1.t': 'Deep reasoning',
    'cap.1.d': 'Thinks a multi-step problem through before answering, with a traceable path.',
    'cap.2.t': 'Web search',
    'cap.2.d': 'Retrieves fresh information when needed and cites verifiable sources.',
    'cap.3.t': 'Long context',
    'cap.3.d': 'Reads a whole manual or filing in one pass without losing the details.',
    'cap.4.t': 'Code & tools',
    'cap.4.d': 'Understands a full repository and calls functions or external tools.',
    'cap.5.t': 'Multimodal',
    'cap.5.d': 'Images, tables and scans — understood before a word is written.',
    'cap.6.t': 'Control & safety',
    'cap.6.d': 'Transparent data use, clear permission boundaries, revocable at any time.',

    'news.eyebrow': 'Updates',
    'news.title': 'Updates',
    'news.1.t': 'Website is live',
    'news.1.d': 'Homepage, capabilities overview and legal pages are ready.',
    'news.2.t': 'Product in development',
    'news.2.d': 'Chat and the Open Platform are not open yet. Progress will be posted here.',

    'footer.slogan': 'Closer to intelligence.',
    'footer.col2': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.disclaimer': 'Disclaimer',
    'footer.col3': 'About',
    'footer.contact': 'Contact',
    'footer.github': 'GitHub',
    'footer.rights': 'All rights reserved',

    'msg.notConfigured': 'This entry is not configured yet and does not work.',
    'msg.sent': 'Chat is still in development and does not work yet.',
    'msg.attached': 'File upload is still in development and does not work yet.',
    'msg.emailCopied': 'Email copied — paste it into your mail client.',
    'msg.theme.light': 'Switched to light mode',
    'msg.theme.dark': 'Switched to dark mode',

    'legal.title': 'Legal',
    'legal.updated': 'Last updated: 2026-10-02',
    'legal.terms.t': 'Terms of Service',
    'legal.terms.p1': 'This site is the official showcase page for Oing. It is fully static: it provides no online service, has no accounts and no paid features.',
    'legal.terms.p2': 'The text, graphics and code on this site are owned by the site or used with permission. You are free to browse it and share links; please contact us before republishing a page in full.',
    'legal.terms.p3': 'The site may change, be suspended or be shut down at any time without notice. Continued browsing constitutes acceptance of these terms.',
    'legal.privacy.t': 'Privacy Policy',
    'legal.privacy.p1': 'This site collects no personal data: no accounts, no form submissions, no tracking, and no third-party analytics or advertising scripts.',
    'legal.privacy.p2': 'The site stores two preferences in your browser\u2019s local storage \u2014 the colour theme and the interface language. They stay on your own device and are never sent anywhere; clearing your browser data removes them.',
    'legal.privacy.p3': 'The site is hosted on GitHub Pages and its DNS is provided by Cloudflare. Those providers may keep access logs (such as IP address and User-Agent) under their own privacy policies. We neither collect nor analyse that data, and we have no access to it.',
    'legal.privacy.p4': 'If you use the question box on the homepage: common questions are answered by replies written into this site and your text never leaves the browser. Only when a question is not covered is it sent to this site\u2019s server endpoint and forwarded to OpenRouter, a model service aggregator, in order to generate a reply. We do not store your question; OpenRouter and its upstream model providers may log requests under their own policies. If you would rather not have that happen, simply do not use that input box \u2014 nothing else on this site requires a network call.',
    'legal.privacy.p5': 'If you email us, your address will only be used to reply to that enquiry. It will not be used for anything else and will not be shared.',
    'legal.disclaimer.t': 'Disclaimer',
    'legal.disclaimer.p1': 'The products and features described here are in development. Descriptions may change at any time and do not constitute a commitment or an offer.',
    'legal.disclaimer.p2': 'The Oing name and graphics are the property of this site. This site is not affiliated with, endorsed by, or authorised by any third-party company, product or trademark.',
    'legal.disclaimer.p3': 'We are not responsible for the content of external sites we link to.',
    'legal.contact.t': 'Contact us',
    'legal.contact.p': 'For any question, feel free to email us.',
    'legal.back': 'Back to home',

    'nf.title': 'Page not found',
    'nf.sub': 'The address you visited does not exist, or has been moved elsewhere.',
    'nf.home': 'Back to home',
  },
};

/** 把指定语言应用到当前文档。 */
window.oingApplyLang = function (lang) {
  var dict = window.OING_I18N || {};
  var table = dict[lang] || dict.zh || {};
  var fallback = dict.zh || {};

  document.documentElement.setAttribute('lang', lang === 'en' ? 'en' : 'zh-CN');

  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    var key = el.getAttribute('data-i18n');
    var value = table[key] || fallback[key];
    if (typeof value === 'string') el.textContent = value;
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
    var key = el.getAttribute('data-i18n-placeholder');
    var value = table[key] || fallback[key];
    if (typeof value === 'string') el.setAttribute('placeholder', value);
  });

  document.querySelectorAll('[data-i18n-label]').forEach(function (el) {
    var key = el.getAttribute('data-i18n-label');
    var value = table[key] || fallback[key];
    if (typeof value === 'string') el.setAttribute('aria-label', value);
  });

  var title = table['meta.title'] || fallback['meta.title'];
  if (title) document.title = title;
  var desc = document.querySelector('meta[name="description"]');
  if (desc) {
    var d = table['meta.description'] || fallback['meta.description'];
    if (d) desc.setAttribute('content', d);
  }
};

/** 取当前语言下的词条，供脚本内部使用。 */
window.oingT = function (key) {
  var dict = window.OING_I18N || {};
  var lang = document.documentElement.lang === 'en' ? 'en' : 'zh';
  var table = dict[lang] || {};
  return table[key] || (dict.zh || {})[key] || key;
};
